spring.application.name=ai_socials
server.port=8080
spring.web.error.whitelabel.enabled=false

# Database H2 configuration
spring.datasource.url=jdbc:h2:file:./data/socialai_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Static resources configuration
spring.web.resources.add-mappings=true
spring.web.resources.cache.period=0
spring.web.resources.static-locations=classpath:/static/,file:./uploads/
spring.mvc.static-path-pattern=/**

# Security configuration
spring.security.enabled=false

# Logging
logging.level.com.demo.ai_socials=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.web.servlet.resource=DEBUG

# JWT (?? ???????????? ??????)
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Ollama Configuration
spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.chat.options.model=deepseek-coder
#spring.ai.ollama.chat.options.model=qwen2.5:7b
spring.ai.ollama.chat.options.model=llama3.2:3b
spring.ai.ollama.chat.options.temperature=0.7